### ISSUE TITLE
Country field expects the name to be capitalised 

### ISSUE THREAD

**Issue by LukaszWituch** [opensourcegeek/stest#1]
Well this is grammatically correct ... but maybe we can get around this, or simply add the stipulation into help, just a thought
|
![screenshot from 2016-12-07 13-18-20](https://cloud.githubusercontent.com/assets/24367717/20969146/a622ddee-bc7f-11e6-8e68-911f09298646.png)

On related note allowing for simple country codes to be used could be nice feature - thinking about getting this as part of a larger test script ....

**Comment by opensourcegeek** [comment]
@LukaszWituch Bug fixed in 0.2.1. I'll add the country codes as searchable in next iteration.

**Comment by opensourcegeek** [comment]
Country code is searchable too now in #a54386ccd3872342ef5ef08d260b61dfa9772128
