### ISSUE TITLE
Most likely just cosmetic

### ISSUE THREAD

**Issue by LukaszWituch** [opensourcegeek/stest#2]
Running 32bit version - on an ancient kernel, really so old it isn't even funny - getting the following 
![zrzut ekranu z 2016-12-14 20-42-35](https://cloud.githubusercontent.com/assets/24367717/21201720/f8569e6a-c243-11e6-9aa1-616f0c648e6f.png)

Test Completes fine so just a cosmetic issue me thinks +1:

**Comment by opensourcegeek** [comment]
Yep, it's one of the long running upload threads timing out (tcp connection) and error message gets printed out to console. Fixed now in f418227cc98b607d132dc0636e77c79c38fcd2c0.
